# To create the conda environment:
# $ conda env create -n my_env_name -f conda.yaml
#
# To update the conda environment:
# $ conda env update -n my_env_name -f conda.yaml
#
# To register the conda environment in Jupyter:
# $ python -m ipykernel install --user --name my_env_name --display-name "Python (my_env_name)"
#

channels:
- conda-forge
- defaults
dependencies:
- python==3.6
- numpy==1.15
- ipykernel==4.6.1
- pip:
  - pandas==0.22.0
  - scipy==1.1.0
  - scikit-learn==0.19.1
  - jupyter==1.0.0
  - matplotlib==2.1.2
  - keras==2.2.2



