# To create the conda environment:
# $ conda env create -f conda.yml -n my_env_name 
#
# To update the conda environment:
# $ conda env update -f conda.yaml -n my_env_name
#
# To register the conda environment in Jupyter:
# $ python -m ipykernel install --user --name my_env_name --display-name "Python (my_env_name)"
#

channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python==3.5
- numpy>=1.13.3
- pytorch==0.4.0
- torchvision==0.2.1
- pip:
  - pandas>=0.22.0
  - scikit-learn>=0.19.1
  - scipy>=1.0.0
  - azure-storage>=0.36.0
  - azure-batch
  - azure-mgmt-scheduler
  - azure
